### PR TITLE
Remove unnecessary Sync

### PR DESCRIPTION
**Pull request by vkill**
Hi @mvniekerk 

Please ref [BoxFuture](https://docs.rs/futures/latest/futures/future/type.BoxFuture.html)

Please review it. thank you.

### CODE REVIEW

**Comment by mvniekerk** [comment]
Hi @vkill 
Thank you for the contribution. If you don't mind, I'm going to hold off on this PR up until 0.6 beta 2 is released and chat with you about it then?

**Comment by mvniekerk** [comment]
Hi @vkill 
0.6 beta 2 has been updated. Can you kindly update your PR please?

**Comment by vkill** [comment]
> Hi @vkill 0.6 beta 2 has been updated. Can you kindly update your PR please?

But I cannot test it now.

```
   Compiling tokio-cron-scheduler v0.6.0-beta.2 (/path/tokio-cron-scheduler)
error[E0601]: `main` function not found in crate `lib`
   --> examples/lib.rs:1:1
    |
1   | / use std::time::Duration;
2   | | use tokio_cron_scheduler::{Job, JobScheduler};
3   | | use tracing::{error, info};
4   | |
...   |
141 | |     sched.shutdown();
142 | | }
    | |_^ consider adding a `main` function to `examples/lib.rs`

```

**Comment by vkill** [comment]
And I have updated based on 0.6 beta 2.

**Comment by mvniekerk** [comment]
Thank you @vkill

**Pull request merged**
